### ISSUE TITLE
Dont work any more

### ISSUE THREAD

**Issue by Techman35** [evertonstz/nitroslim#1]
this is what i get when i execute it on archlinux

1 bernardo@Bernardo-pc ~/Downloads/nitroslim-master % ./nitroslim.py         :(
Traceback (most recent call last):
  File "./nitroslim.py", line 19, in <module>
    BLUR=Configure["Image"]["Blur"]#5
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'Image'

**Comment by evertonstz** [comment]
I've not worked in this project for years, but it seems you're using python 3.8, this project was made under python 3.0, that's probably why you're getting an error.
